### ISSUE TITLE
ValidationError

### ISSUE THREAD

**Issue by Lexy-code** [Mr-KayJayDee/discord-mongodb-economy#4]
An error occured while saving the user : ValidationError: guildMemberData validation failed: level: Cast to Number failed for value "NaN" at path "level"

shows in my logs, im copied what was on the npm website for this, and didnt change anything.
the only commands i have in my file for this is the Creation of the xp and docs, then xp and leaderboards.
i copied three things, and i cant seem to find why im getting this error.

the line its sending me to is 
"var hasLevelUp = await mongoeconomy.attributeXp(message.member.id, message.guild.id, randomXp);"
it sends me to the front of "await"

**Comment by Mr-KayJayDee** [comment]
Hello, con you show me the complete error ? So i can see where this came from.

**Comment by Lexy-code** [comment]
![image](https://user-images.githubusercontent.com/60835424/85932359-74f5e300-b899-11ea-979c-0732a852ebd2.png)

**Comment by Mr-KayJayDee** [comment]
Okay, imma try to fix this now. I think i know what is the problem.

**Comment by Lexy-code** [comment]
👍

**Comment by Mr-KayJayDee** [comment]
Try to get the last update and check if it works.

**Comment by Lexy-code** [comment]
![image](https://user-images.githubusercontent.com/60835424/85932717-8391c980-b89c-11ea-90a8-7c5ee00e0345.png)
same thing. it works in my small server, but when i went into a bigger server with more people, i get the error

**Comment by Mr-KayJayDee** [comment]
Yes i just reverted a wrong code. Can you send me your line 55 in bunny.js ?

**Comment by Lexy-code** [comment]
> Yes i just reverted a wrong code. Can you send me your line 55 in bunny.js ?

https://github.com/Mr-KayJayDee/discord-mongodb-economy/issues/4#issuecomment-650633533

**Comment by Mr-KayJayDee** [comment]
Can you show me the entry of the member that spawn the error ?

**Comment by Lexy-code** [comment]
im not 100% sure what that would be, i would assume its the code?
` var randomXp = Math.floor(Math.random() * 49) + 1;
    var hasLevelUp = await mongoeconomy.attributeXp(message.member.id, message.guild.id, randomXp);
    if (hasLevelUp) {
        // fetch the member
        // return false if there is no entry for the member
        let user = await mongoeconomy.fetchMember(message.member.id, message.guild.id);
        message.channel.send(`${message.member}, congratulations! You have reached the level **${user.level}**. :tada:`).then(m => m.delete(3500));
    }`

**Comment by Mr-KayJayDee** [comment]
Nah, you have to go to MongoDB compass or your atlas cluster. I need the data (from the member that summon the error) from your database.

**Comment by Mr-KayJayDee** [comment]
But yes you can do that too

**Comment by Lexy-code** [comment]
i am not entirely sure where to find the member, i am super new to compass. i only got it working a few days ago

**Comment by Mr-KayJayDee** [comment]
You can follow this tutorial to know how to find a specific key in the database.

https://docs.mongodb.com/compass/master/query/filter/

**Comment by Lexy-code** [comment]
oh, actually. i deleted the doc that held my values, and everything was working fine.
i think i accidentally changed a few things in my user doc for the xp and thats what was causing it

**Comment by Mr-KayJayDee** [comment]
That's what I thought, because the you can't add a number to a string or anything else.

So everything works fine ?

**Comment by Lexy-code** [comment]
yeah. its working fine now.

**Comment by Mr-KayJayDee** [comment]
Okay, feel free to report me if you have any others issues. I'm closing the issue. 👋

**Comment by Lexy-code** [comment]
👍
